=== FallenPlan/TVIK4I_XMLGyak/TVIK4I_0928/CSB_udvar.dtd
<!ELEMENT udvar (gazda|kutya|kakas|tyuk|roka|diszno)*>
<!ELEMENT gazda (#PCDATA)>
<!ATTLIST gazda
        nev CDATA #REQUIRED>
<!ELEMENT kutya (#PCDATA)>
<!ATTLIST kutya
        nev CDATA #REQUIRED>
<!ELEMENT kakas (#PCDATA)>
<!ATTLIST kakas
        id CDATA #REQUIRED>
<!ELEMENT tyuk (#PCDATA)>
<!ATTLIST tyuk
        ferj CDATA #REQUIRED>
<!ELEMENT roka (#PCDATA)>
<!ATTLIST roka
        id CDATA #REQUIRED>
<!ELEMENT diszno (#PCDATA)>
<!ATTLIST diszno
        nev CDATA #REQUIRED>

=== FallenPlan/TVIK4I_XMLGyak/TVIK4I_0928/CSB_udvar.xml
<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE udvar SYSTEM "CSB_udvar.dtd">
<udvar>
    <gazda nev="Alex"/>
    <kutya nev="Nero"></kutya>
    <kakas id="szv_ns3_2jb"/>
    <tyuk ferj="szv_ns3_2jb"/>
    <tyuk ferj="szv_ns3_2jb"/>
    <roka id="szv_ns4_2jb"/>
    <diszno nev="JÃ³zsi"></diszno>
</udvar>
